name: Tests
on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Golang
      uses: actions/setup-go@v1
      with:
        go-version: 1.18.3
    - name: Run Tests
      run: ./scripts/test